[[profiles]]
id = "moonlight-profile-id"
name = "User"

  # ---- Game Mode (gamescope Big Picture) ----
  [[profiles.apps]]
  title = "Steam Big Picture"
  start_virtual_compositor = true
  start_audio_server = true
    [profiles.apps.runner]
    type = "process"

    run_cmd = "bash -lc 'export RUN_GAMESCOPE=true APPIMAGE_EXTRACT_AND_RUN=1; exec /opt/gow/startup-app.sh'"

  # ---- Desktop Mode (sway) ----
  [[profiles.apps]]
  title = "Steam Desktop"
  start_virtual_compositor = true
  start_audio_server = true
    [profiles.apps.runner]
    type = "process"
    run_cmd = "bash -lc 'export RUN_SWAY=1 APPIMAGE_EXTRACT_AND_RUN=1; exec /opt/gow/startup-app.sh'"